#############################################################################
# Makefile for building: QM_visual
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  QM_visual.pro
# Template: app
# Command: /Users/tianxingli/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile QM_visual.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Ilua-5.3.3/src -I../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/tianxingli/Qt/5.7/clang_64/lib
QMAKE         = /Users/tianxingli/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QM_visual1.0.0
DISTDIR = /Users/tianxingli/Desktop/QM_visual/.tmp/QM_visual1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/tianxingli/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/tianxingli/Qt/5.7/clang_64/lib -L/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src/ -llua -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		glwidget.cpp \
		data.cpp \
		window.cpp \
		camera.cpp \
		ae/ae.c \
		equationparser.cpp \
		widgetaddons.cpp \
		helpers.cpp qrc_resources.cpp \
		moc_window.cpp \
		moc_glwidget.cpp \
		moc_data.cpp \
		moc_camera.cpp \
		moc_widgetaddons.cpp
OBJECTS       = main.o \
		glwidget.o \
		data.o \
		window.o \
		camera.o \
		ae.o \
		equationparser.o \
		widgetaddons.o \
		helpers.o \
		qrc_resources.o \
		moc_window.o \
		moc_glwidget.o \
		moc_data.o \
		moc_camera.o \
		moc_widgetaddons.o
DIST          = ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		QM_visual.pro window.h \
		glwidget.h \
		data.h \
		camera.h \
		ae/ae.h \
		equationparser.h \
		widgetaddons.h \
		helpers.h main.cpp \
		glwidget.cpp \
		data.cpp \
		window.cpp \
		camera.cpp \
		ae/ae.c \
		equationparser.cpp \
		widgetaddons.cpp \
		helpers.cpp
QMAKE_TARGET  = QM_visual
DESTDIR       = 
TARGET        = QM_visual


first: all
####### Build rules

$(TARGET): /Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src/liblua.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QM_visual.pro ../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		QM_visual.pro \
		resources.qrc \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile QM_visual.pro
../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
QM_visual.pro:
resources.qrc:
../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.7/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile QM_visual.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents window.h glwidget.h data.h camera.h ae/ae.h equationparser.h widgetaddons.h helpers.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp glwidget.cpp data.cpp window.cpp camera.cpp ae/ae.c equationparser.cpp widgetaddons.cpp helpers.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../Qt/5.7/clang_64/bin/rcc \
		icon1.png \
		ted.png \
		face.png \
		buttons/continuous_dark.png \
		buttons/continuous_dark_active.png \
		buttons/pause.png \
		buttons/observe.png \
		buttons/classical_active.png \
		buttons/play.png \
		buttons/restart_active.png \
		buttons/pause_active.png \
		buttons/continuous.png \
		buttons/continuous_active.png \
		buttons/restart_fill.png \
		buttons/classical.png \
		buttons/discrete_active.png \
		buttons/play_active2.png \
		buttons/restart.png \
		buttons/play2.png \
		buttons/play_active.png \
		buttons/observe_fill.png \
		buttons/observe_active.png \
		buttons/discrete.png \
		buttons/discrete_dark.png \
		buttons/discrete_dark_active.png \
		styleSheetBlue.qss \
		cmaps/inferno_cmap
	/Users/tianxingli/Qt/5.7/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_window.cpp moc_glwidget.cpp moc_data.cpp moc_camera.cpp moc_widgetaddons.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_glwidget.cpp moc_data.cpp moc_camera.cpp moc_widgetaddons.cpp
moc_window.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTreeWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHeaderView \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSizePolicy \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QDesktopServices \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		glwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h \
		camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		widgetaddons.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QAbstractTextDocumentLayout \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabBar \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		window.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/tianxingli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/tianxingli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/tianxingli/Desktop/QM_visual -I/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/tianxingli/Qt/5.7/clang_64/lib window.h -o moc_window.cpp

moc_glwidget.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h \
		camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		glwidget.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/tianxingli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/tianxingli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/tianxingli/Desktop/QM_visual -I/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/tianxingli/Qt/5.7/clang_64/lib glwidget.h -o moc_glwidget.cpp

moc_data.cpp: ../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h \
		data.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/tianxingli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/tianxingli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/tianxingli/Desktop/QM_visual -I/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/tianxingli/Qt/5.7/clang_64/lib data.h -o moc_data.cpp

moc_camera.cpp: ../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		camera.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/tianxingli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/tianxingli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/tianxingli/Desktop/QM_visual -I/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/tianxingli/Qt/5.7/clang_64/lib camera.h -o moc_camera.cpp

moc_widgetaddons.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QAbstractTextDocumentLayout \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabBar \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		widgetaddons.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/tianxingli/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/tianxingli/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/tianxingli/Desktop/QM_visual -I/Users/tianxingli/Desktop/QM_visual/lua-5.3.3/src -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers -I/Users/tianxingli/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/tianxingli/Qt/5.7/clang_64/lib widgetaddons.h -o moc_widgetaddons.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		window.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTreeWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHeaderView \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSizePolicy \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QDesktopServices \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		glwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		ae/ae.h \
		equationparser.h \
		camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		widgetaddons.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QAbstractTextDocumentLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabBar \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glwidget.o: glwidget.cpp glwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h \
		camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

data.o: data.cpp data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

window.o: window.cpp window.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTreeWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHeaderView \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSizePolicy \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QDesktopServices \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		glwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		data.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFuture \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../../Qt/5.7/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		ae/ae.h \
		equationparser.h \
		camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		widgetaddons.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QAbstractTextDocumentLayout \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabBar \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

camera.o: camera.cpp camera.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

ae.o: ae/ae.c ae/ae.h \
		ae/lmathx.c \
		lua-5.3.3/src/lua.hpp \
		lua-5.3.3/src/lua.h \
		lua-5.3.3/src/luaconf.h \
		lua-5.3.3/src/lualib.h \
		lua-5.3.3/src/lauxlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ae.o ae/ae.c

equationparser.o: equationparser.cpp equationparser.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		ae/ae.h \
		helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equationparser.o equationparser.cpp

widgetaddons.o: widgetaddons.cpp widgetaddons.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QAbstractTextDocumentLayout \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTabBar \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widgetaddons.o widgetaddons.cpp

helpers.o: helpers.cpp helpers.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvector.h \
		ae/ae.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o helpers.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_data.o: moc_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_data.o moc_data.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_widgetaddons.o: moc_widgetaddons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widgetaddons.o moc_widgetaddons.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

